### PR TITLE
Finished feed_animal.py

### PR DESCRIPTION
**Pull request by RockMurdock**
## Description

added the feed_animal.py file
## Motivation and Context

feeds the starving animals

currently animals can't eat anything
## How Has This Been Tested?

went through all animals and tested each one

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by MatthewScott32 — APPROVED** [review]
Looks good

**Comment by mister-michael** [comment]
makes sense the dude with 24 dogs did such a sick job with feed_animal

**Comment by kurtkrafft1** [comment]
💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ we rule💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳ 💯 🏌️ 💯 ⛳

**Comment by jcksnparsons** [comment]
Crushin sandos and rippin rocket sauce

**Review by kurtkrafft1 — APPROVED** [review]

**Review by mister-michael — APPROVED** [review]
this is much better than that shitty walk you took yesterday

**Pull request merged**
